/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package elaprendiz.ventanas.paneles;

import elaprendiz.modelbd.Usuario;
import java.awt.BorderLayout;
import java.awt.Component;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author programadorbipolar
 */
public class PanelAsignarPermisos extends javax.swing.JPanel {

    /**
     * Creates new form PanelAsignarPermisos
     */
    private JOptionPane op;
    private Usuario usuario;
    private PanelAutorizacion pnlAuth;
    public PanelAsignarPermisos(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        pnlAuth = new PanelAutorizacion(this.usuario);
        this.add(pnlAuth, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void getOptionPane()
    {
        if(op != null)
        {
            return;
        }
        Component pdr =this.getParent(); 
        while(pdr.getParent() != null)
        {
            if(pdr instanceof JOptionPane)
            {
                op = (JOptionPane)pdr;
                break;
            }            
            pdr = pdr.getParent();
        }
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonRect1 = new elaprendiz.gui.button.ButtonRect();
        buttonRect2 = new elaprendiz.gui.button.ButtonRect();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.GridBagLayout());

        buttonRect1.setText("Finalizar");
        jPanel1.add(buttonRect1, new java.awt.GridBagConstraints());

        buttonRect2.setText("Cancelar");
        buttonRect2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRect2ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonRect2, new java.awt.GridBagConstraints());

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRect2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRect2ActionPerformed
       getOptionPane();
       op.setValue(1);
    }//GEN-LAST:event_buttonRect2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private elaprendiz.gui.button.ButtonRect buttonRect1;
    private elaprendiz.gui.button.ButtonRect buttonRect2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public JLabel getLbAviso() {
        return new JLabel();
    }
}
